### ISSUE TITLE
Server errors when mentioning user twice in post

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#502] opened 2019-08-21 10:00 UTC
Looks like the unique constraint on post comment mentions is failing when trying to mention a user twice under the same post.

/okuna/okuna-api/issues/824/?query=is:unresolved

**Comment by lifenautjoe** [comment] 2019-08-21 10:09
On a comment reply, mention x one, and then mention x, together y on a consequent reply.

**Comment by lifenautjoe** [comment] 2019-08-26 09:04
Another reported issue by Oliver, okuna/okuna-api/issues/63/?query=is:unresolved

**Comment by lifenautjoe** [comment] 2019-08-26 11:46
Some more issues related to mentions

<img width="411" alt="image" src="https://user-images.githubusercontent.com/12737509/63688534-f4450100-c807-11e9-9fa3-f5749dcc342b.png">

**Comment by lifenautjoe** [comment] 2019-09-01 12:29
Another issue on okuna/okuna-api/issues/63/?query=is:unresolved

**Comment by uiboy** [comment] 2019-09-29 11:38
Confirmed with tom, this was fixed with the update 0.53, and is not happening anymore.

**Comment by uiboy** [comment] 2019-10-01 14:49
Looks like it is still happening https://sentry.openbook.social/okuna/okuna-api/issues/10989/?query=is:unresolved

**Comment by lifenautjoe** [comment] 2019-10-09 12:05
Dang it, I can't reproduce :-(

**Comment by uiboy** [comment] 2019-10-09 14:15
Yea i had the same , tried so many diff ways :(

**Closed** 2019-10-09 18:27 UTC
Labels: bug, could not reproduce, priority:critical
